# Generated by Django 4.2 on 2023-04-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_doctorcategorymodel_alter_user_options_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='work_time_end',
            field=models.TimeField(default='21:00'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='work_time_start',
            field=models.TimeField(default='8:00'),
        ),
    ]
