# Generated by Django 4.2 on 2023-04-28 15:20

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_doctorsservice_doctor_work_time_end_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
    ]
