# Generated by Django 4.2 on 2023-04-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='category',
        ),
    ]
