# Generated by Django 4.2 on 2023-04-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_doctor_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorcategorymodel',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='doctorsservice',
            options={'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.RenameField(
            model_name='doctorcategorymodel',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='doctorsservice',
            old_name='name',
            new_name='service',
        ),
    ]
