# Generated by Django 4.2 on 2023-04-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_appointment_service_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(default=1200),
            preserve_default=False,
        ),
    ]
